# Generated by Django 3.2.12 on 2022-04-13 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILINGCABINET_DOCUMENT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("question", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("documents_needed", models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TM", "Manual Annotation"),
                            ("TA", "Automated Annotations"),
                        ],
                        default="TM",
                        max_length=2,
                    ),
                ),
                ("final", models.BooleanField(default=False)),
                ("value", models.BooleanField(null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.FILINGCABINET_DOCUMENT_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_annotations",
                        to="fcdocs_annotation.feature",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "feature", "document")},
            },
        ),
    ]
