# Generated by Django 3.2.12 on 2022-04-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fcdocs_annotation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="describtion",
            new_name="description",
        ),
    ]
