# Generated by Django 3.2.12 on 2022-04-27 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILINGCABINET_DOCUMENT_MODEL),
        ("fcdocs_annotation", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="featureannotation",
            unique_together={("feature", "document")},
        ),
        migrations.RemoveField(
            model_name="featureannotation",
            name="final",
        ),
        migrations.RemoveField(
            model_name="featureannotation",
            name="session",
        ),
        migrations.CreateModel(
            name="FeatureAnnotationDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(blank=True, max_length=255)),
                ("value", models.BooleanField(null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.FILINGCABINET_DOCUMENT_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_annotation_drafts",
                        to="fcdocs_annotation.feature",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "feature", "document")},
            },
        ),
    ]
