# Generated by Django 3.2.12 on 2022-04-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcdocs_annotation", "0002_auto_20220427_1013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureannotation",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fcdocs_annotation_featureannotation_annotations",
                to="fcdocs_annotation.feature",
            ),
        ),
        migrations.AlterField(
            model_name="featureannotationdraft",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fcdocs_annotation_featureannotationdraft_annotations",
                to="fcdocs_annotation.feature",
            ),
        ),
    ]
