# Generated by Django 3.2.12 on 2022-04-05 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcdocs_annotation', '0003_feature_annotations_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureannotation',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcdocs_annotation.feature'),
        ),
        migrations.AddField(
            model_name='featureannotation',
            name='value',
            field=models.BooleanField(null=True),
        ),
    ]
