# Generated by Django 3.2.13 on 2022-08-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcdocs_annotation", "0003_auto_20220427_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="model_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
