# Generated by Django 3.2.12 on 2022-04-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcdocs_annotation", "0004_auto_20220405_1021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureannotation",
            name="feature",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_annotations",
                to="fcdocs_annotation.feature",
            ),
        ),
    ]
