# Generated by Django 4.0.7 on 2022-09-23 11:17

import django.db.models.deletion
from django.db import migrations, models

import fcdocs_annotate.annotation.models.feature


class Migration(migrations.Migration):

    dependencies = [
        ("fcdocs_annotation", "0004_feature_model_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="model_path",
            field=models.FileField(
                blank=True,
                max_length=500,
                upload_to=fcdocs_annotate.annotation.models.feature.get_upload_modelfile_path,
            ),
        ),
        migrations.AlterField(
            model_name="featureannotation",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_annotations",
                to="fcdocs_annotation.feature",
            ),
        ),
        migrations.AlterField(
            model_name="featureannotationdraft",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_annotations",
                to="fcdocs_annotation.feature",
            ),
        ),
    ]
