# Generated by Django 4.0.7 on 2022-09-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcdocs_annotation", "0005_alter_feature_model_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureannotation",
            name="score",
            field=models.FloatField(null=True),
        ),
    ]
