# Generated by Django 3.2.12 on 2022-04-12 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILINGCABINET_DOCUMENT_MODEL),
        ("fcdocs_annotation", "0005_alter_featureannotation_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureannotation",
            name="session",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="featureannotation",
            name="feature",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_annotations",
                to="fcdocs_annotation.feature",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="featureannotation",
            unique_together={("session", "feature", "document")},
        ),
        migrations.RemoveField(
            model_name="featureannotation",
            name="features",
        ),
    ]
